export const IMAGES = [
  {
    id: 1,
    title: "Lorem ipsum",
    description: "Lorem ipsum",
    url: "https://www.w3schools.com/w3images/wedding.jpg",
  },
  {
    id: 2,
    title: "Lorem ipsum",
    description: "Lorem ipsum",
    url: "https://www.w3schools.com/w3images/rocks.jpg",
  },
  {
    id: 3,
    title: "Lorem ipsum",
    description: "Lorem ipsum",
    url: "https://www.w3schools.com/w3images/falls2.jpg",
  },
  {
    id: 4,
    title: "Lorem ipsum",
    description: "Lorem ipsum",
    url: "https://www.w3schools.com/w3images/paris.jpg",
  },
  {
    id: 5,
    title: "Lorem ipsum",
    description: "Lorem ipsum",
    url: "https://www.w3schools.com/w3images/nature.jpg",
  },
  {
    id: 6,
    title: "Lorem ipsum",
    description: "Lorem ipsum",
    url: "https://www.w3schools.com/w3images/mist.jpg",
  },
  {
    id: 7,
    title: "Lorem ipsum",
    description: "Lorem ipsum",
    url: "https://www.w3schools.com/w3images/paris.jpg",
  },
  {
    id: 8,
    title: "Lorem ipsum",
    description: "Lorem ipsum",
    url: "https://www.w3schools.com/w3images/underwater.jpg",
  },
  {
    id: 9,
    title: "Lorem ipsum",
    description: "Lorem ipsum",
    url: "https://www.w3schools.com/w3images/ocean.jpg",
  },
  {
    id: 10,
    title: "Lorem ipsum",
    description: "Lorem ipsum",
    url: "https://www.w3schools.com/w3images/wedding.jpg",
  },
  {
    id: 11,
    title: "Lorem ipsum",
    description: "Lorem ipsum",
    url: "https://www.w3schools.com/w3images/mountainskies.jpg",
  },
  {
    id: 12,
    title: "Lorem ipsum",
    description: "Lorem ipsum",
    url: "https://www.w3schools.com/w3images/rocks.jpg",
  },
  {
    id: 13,
    title: "Lorem ipsum",
    description: "Lorem ipsum",
    url: "https://www.w3schools.com/w3images/underwater.jpg",
  },
  {
    id: 14,
    title: "Lorem ipsum",
    description: "Lorem ipsum",
    url: "https://www.w3schools.com/w3images/wedding.jpg",
  },
  {
    id: 15,
    title: "Lorem ipsum",
    description: "Lorem ipsum",
    url: "https://www.w3schools.com/w3images/rocks.jpg",
  },
  {
    id: 16,
    title: "Lorem ipsum",
    description: "Lorem ipsum",
    url: "https://www.w3schools.com/w3images/falls2.jpg",
  },

  {
    id: 17,
    title: "Lorem ipsum",
    description: "Lorem ipsum",
    url: "https://www.w3schools.com/w3images/paris.jpg",
  },
  {
    id: 18,
    title: "Lorem ipsum",
    description: "Lorem ipsum",
    url: "https://www.w3schools.com/w3images/nature.jpg",
  },
  {
    id: 19,
    title: "Lorem ipsum",
    description: "Lorem ipsum",
    url: "https://www.w3schools.com/w3images/mist.jpg",
  },
  {
    id: 20,
    title: "Lorem ipsum",
    description: "Lorem ipsum",
    url: "https://www.w3schools.com/w3images/paris.jpg",
  },
  {
    id: 21,
    title: "Lorem ipsum",
    description: "Lorem ipsum",
    url: "https://www.w3schools.com/w3images/underwater.jpg",
  },
  {
    id: 22,
    title: "Lorem ipsum",
    description: "Lorem ipsum",
    url: "https://www.w3schools.com/w3images/ocean.jpg",
  },
  {
    id: 23,
    title: "Lorem ipsum",
    description: "Lorem ipsum",
    url: "https://www.w3schools.com/w3images/wedding.jpg",
  },
  {
    id: 24,
    title: "Lorem ipsum",
    description: "Lorem ipsum",
    url: "https://www.w3schools.com/w3images/mountainskies.jpg",
  },
  {
    id: 25,
    title: "Lorem ipsum",
    description: "Lorem ipsum",
    url: "https://www.w3schools.com/w3images/rocks.jpg",
  },
  {
    id: 26,
    title: "Lorem ipsum",
    description: "Lorem ipsum",
    url: "https://www.w3schools.com/w3images/underwater.jpg",
  },
];
